/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as ServicosRouteImport } from './routes/servicos'
import { Route as RegistoRouteImport } from './routes/registo'
import { Route as RedesRouteImport } from './routes/redes'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as PrecosRouteImport } from './routes/precos'
import { Route as OrcamentoRouteImport } from './routes/orcamento'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InformaticaRouteImport } from './routes/informatica'
import { Route as GaleriaRouteImport } from './routes/galeria'
import { Route as ContactosRouteImport } from './routes/contactos'
import { Route as ContaRouteImport } from './routes/conta'
import { Route as BalcaoRouteImport } from './routes/balcao'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicosIndexRouteImport } from './routes/servicos.index'
import { Route as LojaIndexRouteImport } from './routes/loja.index'
import { Route as HubIndexRouteImport } from './routes/hub.index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BalcaoIndexRouteImport } from './routes/balcao.index'
import { Route as ServicosSlugRouteImport } from './routes/servicos.$slug'
import { Route as LojaPapelariaRouteImport } from './routes/loja.papelaria'
import { Route as LojaCheckoutRouteImport } from './routes/loja.checkout'
import { Route as LojaCarrinhoRouteImport } from './routes/loja.carrinho'
import { Route as HubUploadRouteImport } from './routes/hub.upload'
import { Route as HubNoticiasRouteImport } from './routes/hub.noticias'
import { Route as HubFavoritosRouteImport } from './routes/hub.favoritos'
import { Route as HubExplorarRouteImport } from './routes/hub.explorar'
import { Route as HubExamesRouteImport } from './routes/hub.exames'
import { Route as HubDocumentosRouteImport } from './routes/hub.documentos'
import { Route as HubCvRouteImport } from './routes/hub.cv'
import { Route as HubCreditosRouteImport } from './routes/hub.creditos'
import { Route as HubCartasRouteImport } from './routes/hub.cartas'
import { Route as HubBolsasRouteImport } from './routes/hub.bolsas'
import { Route as GaleriaSlugRouteImport } from './routes/galeria.$slug'
import { Route as ContaRevisoesRouteImport } from './routes/conta.revisoes'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as BalcaoStockRouteImport } from './routes/balcao.stock'
import { Route as BalcaoServicosRouteImport } from './routes/balcao.servicos'
import { Route as BalcaoRevisoesPrecosRouteImport } from './routes/balcao.revisoes-precos'
import { Route as BalcaoRevisoesRouteImport } from './routes/balcao.revisoes'
import { Route as BalcaoProdutosRouteImport } from './routes/balcao.produtos'
import { Route as BalcaoPrecosRouteImport } from './routes/balcao.precos'
import { Route as BalcaoPedidosRouteImport } from './routes/balcao.pedidos'
import { Route as BalcaoPagamentosRouteImport } from './routes/balcao.pagamentos'
import { Route as BalcaoNotificacoesRouteImport } from './routes/balcao.notificacoes'
import { Route as BalcaoNoticiasRouteImport } from './routes/balcao.noticias'
import { Route as BalcaoNewsletterRouteImport } from './routes/balcao.newsletter'
import { Route as BalcaoHubRouteImport } from './routes/balcao.hub'
import { Route as BalcaoHeroRouteImport } from './routes/balcao.hero'
import { Route as BalcaoGaleriaRouteImport } from './routes/balcao.galeria'
import { Route as BalcaoExamesRouteImport } from './routes/balcao.exames'
import { Route as BalcaoEntregasRouteImport } from './routes/balcao.entregas'
import { Route as BalcaoCvTemplatesRouteImport } from './routes/balcao.cv-templates'
import { Route as BalcaoCvRouteImport } from './routes/balcao.cv'
import { Route as BalcaoCreditosRouteImport } from './routes/balcao.creditos'
import { Route as BalcaoCartasRouteImport } from './routes/balcao.cartas'
import { Route as BalcaoCampanhasRouteImport } from './routes/balcao.campanhas'
import { Route as BalcaoBolsasRouteImport } from './routes/balcao.bolsas'
import { Route as BalcaoBlogRouteImport } from './routes/balcao.blog'
import { Route as BalcaoAtividadeRouteImport } from './routes/balcao.atividade'
import { Route as BalcaoAiPlaygroundRouteImport } from './routes/balcao.ai-playground'
import { Route as HubNoticiasIndexRouteImport } from './routes/hub.noticias.index'
import { Route as HubBolsasIndexRouteImport } from './routes/hub.bolsas.index'
import { Route as LojaProdutoIdRouteImport } from './routes/loja.produto.$id'
import { Route as LojaPedidoIdRouteImport } from './routes/loja.pedido.$id'
import { Route as HubNoticiasIdRouteImport } from './routes/hub.noticias.$id'
import { Route as HubExamesIdRouteImport } from './routes/hub.exames.$id'
import { Route as HubDocumentoIdRouteImport } from './routes/hub.documento.$id'
import { Route as HubBolsasIdRouteImport } from './routes/hub.bolsas.$id'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicosRoute = ServicosRouteImport.update({
  id: '/servicos',
  path: '/servicos',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistoRoute = RegistoRouteImport.update({
  id: '/registo',
  path: '/registo',
  getParentRoute: () => rootRouteImport,
} as any)
const RedesRoute = RedesRouteImport.update({
  id: '/redes',
  path: '/redes',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const PrecosRoute = PrecosRouteImport.update({
  id: '/precos',
  path: '/precos',
  getParentRoute: () => rootRouteImport,
} as any)
const OrcamentoRoute = OrcamentoRouteImport.update({
  id: '/orcamento',
  path: '/orcamento',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InformaticaRoute = InformaticaRouteImport.update({
  id: '/informatica',
  path: '/informatica',
  getParentRoute: () => rootRouteImport,
} as any)
const GaleriaRoute = GaleriaRouteImport.update({
  id: '/galeria',
  path: '/galeria',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactosRoute = ContactosRouteImport.update({
  id: '/contactos',
  path: '/contactos',
  getParentRoute: () => rootRouteImport,
} as any)
const ContaRoute = ContaRouteImport.update({
  id: '/conta',
  path: '/conta',
  getParentRoute: () => rootRouteImport,
} as any)
const BalcaoRoute = BalcaoRouteImport.update({
  id: '/balcao',
  path: '/balcao',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicosIndexRoute = ServicosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ServicosRoute,
} as any)
const LojaIndexRoute = LojaIndexRouteImport.update({
  id: '/loja/',
  path: '/loja/',
  getParentRoute: () => rootRouteImport,
} as any)
const HubIndexRoute = HubIndexRouteImport.update({
  id: '/hub/',
  path: '/hub/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BalcaoIndexRoute = BalcaoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BalcaoRoute,
} as any)
const ServicosSlugRoute = ServicosSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ServicosRoute,
} as any)
const LojaPapelariaRoute = LojaPapelariaRouteImport.update({
  id: '/loja/papelaria',
  path: '/loja/papelaria',
  getParentRoute: () => rootRouteImport,
} as any)
const LojaCheckoutRoute = LojaCheckoutRouteImport.update({
  id: '/loja/checkout',
  path: '/loja/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const LojaCarrinhoRoute = LojaCarrinhoRouteImport.update({
  id: '/loja/carrinho',
  path: '/loja/carrinho',
  getParentRoute: () => rootRouteImport,
} as any)
const HubUploadRoute = HubUploadRouteImport.update({
  id: '/hub/upload',
  path: '/hub/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const HubNoticiasRoute = HubNoticiasRouteImport.update({
  id: '/hub/noticias',
  path: '/hub/noticias',
  getParentRoute: () => rootRouteImport,
} as any)
const HubFavoritosRoute = HubFavoritosRouteImport.update({
  id: '/hub/favoritos',
  path: '/hub/favoritos',
  getParentRoute: () => rootRouteImport,
} as any)
const HubExplorarRoute = HubExplorarRouteImport.update({
  id: '/hub/explorar',
  path: '/hub/explorar',
  getParentRoute: () => rootRouteImport,
} as any)
const HubExamesRoute = HubExamesRouteImport.update({
  id: '/hub/exames',
  path: '/hub/exames',
  getParentRoute: () => rootRouteImport,
} as any)
const HubDocumentosRoute = HubDocumentosRouteImport.update({
  id: '/hub/documentos',
  path: '/hub/documentos',
  getParentRoute: () => rootRouteImport,
} as any)
const HubCvRoute = HubCvRouteImport.update({
  id: '/hub/cv',
  path: '/hub/cv',
  getParentRoute: () => rootRouteImport,
} as any)
const HubCreditosRoute = HubCreditosRouteImport.update({
  id: '/hub/creditos',
  path: '/hub/creditos',
  getParentRoute: () => rootRouteImport,
} as any)
const HubCartasRoute = HubCartasRouteImport.update({
  id: '/hub/cartas',
  path: '/hub/cartas',
  getParentRoute: () => rootRouteImport,
} as any)
const HubBolsasRoute = HubBolsasRouteImport.update({
  id: '/hub/bolsas',
  path: '/hub/bolsas',
  getParentRoute: () => rootRouteImport,
} as any)
const GaleriaSlugRoute = GaleriaSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => GaleriaRoute,
} as any)
const ContaRevisoesRoute = ContaRevisoesRouteImport.update({
  id: '/revisoes',
  path: '/revisoes',
  getParentRoute: () => ContaRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BalcaoStockRoute = BalcaoStockRouteImport.update({
  id: '/stock',
  path: '/stock',
  getParentRoute: () => BalcaoRoute,
} as any)
const BalcaoServicosRoute = BalcaoServicosRouteImport.update({
  id: '/servicos',
  path: '/servicos',
  getParentRoute: () => BalcaoRoute,
} as any)
const BalcaoRevisoesPrecosRoute = BalcaoRevisoesPrecosRouteImport.update({
  id: '/revisoes-precos',
  path: '/revisoes-precos',
  getParentRoute: () => BalcaoRoute,
} as any)
const BalcaoRevisoesRoute = BalcaoRevisoesRouteImport.update({
  id: '/revisoes',
  path: '/revisoes',
  getParentRoute: () => BalcaoRoute,
} as any)
const BalcaoProdutosRoute = BalcaoProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => BalcaoRoute,
} as any)
const BalcaoPrecosRoute = BalcaoPrecosRouteImport.update({
  id: '/precos',
  path: '/precos',
  getParentRoute: () => BalcaoRoute,
} as any)
const BalcaoPedidosRoute = BalcaoPedidosRouteImport.update({
  id: '/pedidos',
  path: '/pedidos',
  getParentRoute: () => BalcaoRoute,
} as any)
const BalcaoPagamentosRoute = BalcaoPagamentosRouteImport.update({
  id: '/pagamentos',
  path: '/pagamentos',
  getParentRoute: () => BalcaoRoute,
} as any)
const BalcaoNotificacoesRoute = BalcaoNotificacoesRouteImport.update({
  id: '/notificacoes',
  path: '/notificacoes',
  getParentRoute: () => BalcaoRoute,
} as any)
const BalcaoNoticiasRoute = BalcaoNoticiasRouteImport.update({
  id: '/noticias',
  path: '/noticias',
  getParentRoute: () => BalcaoRoute,
} as any)
const BalcaoNewsletterRoute = BalcaoNewsletterRouteImport.update({
  id: '/newsletter',
  path: '/newsletter',
  getParentRoute: () => BalcaoRoute,
} as any)
const BalcaoHubRoute = BalcaoHubRouteImport.update({
  id: '/hub',
  path: '/hub',
  getParentRoute: () => BalcaoRoute,
} as any)
const BalcaoHeroRoute = BalcaoHeroRouteImport.update({
  id: '/hero',
  path: '/hero',
  getParentRoute: () => BalcaoRoute,
} as any)
const BalcaoGaleriaRoute = BalcaoGaleriaRouteImport.update({
  id: '/galeria',
  path: '/galeria',
  getParentRoute: () => BalcaoRoute,
} as any)
const BalcaoExamesRoute = BalcaoExamesRouteImport.update({
  id: '/exames',
  path: '/exames',
  getParentRoute: () => BalcaoRoute,
} as any)
const BalcaoEntregasRoute = BalcaoEntregasRouteImport.update({
  id: '/entregas',
  path: '/entregas',
  getParentRoute: () => BalcaoRoute,
} as any)
const BalcaoCvTemplatesRoute = BalcaoCvTemplatesRouteImport.update({
  id: '/cv-templates',
  path: '/cv-templates',
  getParentRoute: () => BalcaoRoute,
} as any)
const BalcaoCvRoute = BalcaoCvRouteImport.update({
  id: '/cv',
  path: '/cv',
  getParentRoute: () => BalcaoRoute,
} as any)
const BalcaoCreditosRoute = BalcaoCreditosRouteImport.update({
  id: '/creditos',
  path: '/creditos',
  getParentRoute: () => BalcaoRoute,
} as any)
const BalcaoCartasRoute = BalcaoCartasRouteImport.update({
  id: '/cartas',
  path: '/cartas',
  getParentRoute: () => BalcaoRoute,
} as any)
const BalcaoCampanhasRoute = BalcaoCampanhasRouteImport.update({
  id: '/campanhas',
  path: '/campanhas',
  getParentRoute: () => BalcaoRoute,
} as any)
const BalcaoBolsasRoute = BalcaoBolsasRouteImport.update({
  id: '/bolsas',
  path: '/bolsas',
  getParentRoute: () => BalcaoRoute,
} as any)
const BalcaoBlogRoute = BalcaoBlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => BalcaoRoute,
} as any)
const BalcaoAtividadeRoute = BalcaoAtividadeRouteImport.update({
  id: '/atividade',
  path: '/atividade',
  getParentRoute: () => BalcaoRoute,
} as any)
const BalcaoAiPlaygroundRoute = BalcaoAiPlaygroundRouteImport.update({
  id: '/ai-playground',
  path: '/ai-playground',
  getParentRoute: () => BalcaoRoute,
} as any)
const HubNoticiasIndexRoute = HubNoticiasIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HubNoticiasRoute,
} as any)
const HubBolsasIndexRoute = HubBolsasIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HubBolsasRoute,
} as any)
const LojaProdutoIdRoute = LojaProdutoIdRouteImport.update({
  id: '/loja/produto/$id',
  path: '/loja/produto/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const LojaPedidoIdRoute = LojaPedidoIdRouteImport.update({
  id: '/loja/pedido/$id',
  path: '/loja/pedido/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const HubNoticiasIdRoute = HubNoticiasIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => HubNoticiasRoute,
} as any)
const HubExamesIdRoute = HubExamesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => HubExamesRoute,
} as any)
const HubDocumentoIdRoute = HubDocumentoIdRouteImport.update({
  id: '/hub/documento/$id',
  path: '/hub/documento/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const HubBolsasIdRoute = HubBolsasIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => HubBolsasRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/balcao': typeof BalcaoRouteWithChildren
  '/conta': typeof ContaRouteWithChildren
  '/contactos': typeof ContactosRoute
  '/galeria': typeof GaleriaRouteWithChildren
  '/informatica': typeof InformaticaRoute
  '/login': typeof LoginRoute
  '/orcamento': typeof OrcamentoRoute
  '/precos': typeof PrecosRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/redes': typeof RedesRoute
  '/registo': typeof RegistoRoute
  '/servicos': typeof ServicosRouteWithChildren
  '/sobre': typeof SobreRoute
  '/terms': typeof TermsRoute
  '/balcao/ai-playground': typeof BalcaoAiPlaygroundRoute
  '/balcao/atividade': typeof BalcaoAtividadeRoute
  '/balcao/blog': typeof BalcaoBlogRoute
  '/balcao/bolsas': typeof BalcaoBolsasRoute
  '/balcao/campanhas': typeof BalcaoCampanhasRoute
  '/balcao/cartas': typeof BalcaoCartasRoute
  '/balcao/creditos': typeof BalcaoCreditosRoute
  '/balcao/cv': typeof BalcaoCvRoute
  '/balcao/cv-templates': typeof BalcaoCvTemplatesRoute
  '/balcao/entregas': typeof BalcaoEntregasRoute
  '/balcao/exames': typeof BalcaoExamesRoute
  '/balcao/galeria': typeof BalcaoGaleriaRoute
  '/balcao/hero': typeof BalcaoHeroRoute
  '/balcao/hub': typeof BalcaoHubRoute
  '/balcao/newsletter': typeof BalcaoNewsletterRoute
  '/balcao/noticias': typeof BalcaoNoticiasRoute
  '/balcao/notificacoes': typeof BalcaoNotificacoesRoute
  '/balcao/pagamentos': typeof BalcaoPagamentosRoute
  '/balcao/pedidos': typeof BalcaoPedidosRoute
  '/balcao/precos': typeof BalcaoPrecosRoute
  '/balcao/produtos': typeof BalcaoProdutosRoute
  '/balcao/revisoes': typeof BalcaoRevisoesRoute
  '/balcao/revisoes-precos': typeof BalcaoRevisoesPrecosRoute
  '/balcao/servicos': typeof BalcaoServicosRoute
  '/balcao/stock': typeof BalcaoStockRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/conta/revisoes': typeof ContaRevisoesRoute
  '/galeria/$slug': typeof GaleriaSlugRoute
  '/hub/bolsas': typeof HubBolsasRouteWithChildren
  '/hub/cartas': typeof HubCartasRoute
  '/hub/creditos': typeof HubCreditosRoute
  '/hub/cv': typeof HubCvRoute
  '/hub/documentos': typeof HubDocumentosRoute
  '/hub/exames': typeof HubExamesRouteWithChildren
  '/hub/explorar': typeof HubExplorarRoute
  '/hub/favoritos': typeof HubFavoritosRoute
  '/hub/noticias': typeof HubNoticiasRouteWithChildren
  '/hub/upload': typeof HubUploadRoute
  '/loja/carrinho': typeof LojaCarrinhoRoute
  '/loja/checkout': typeof LojaCheckoutRoute
  '/loja/papelaria': typeof LojaPapelariaRoute
  '/servicos/$slug': typeof ServicosSlugRoute
  '/balcao/': typeof BalcaoIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/hub/': typeof HubIndexRoute
  '/loja/': typeof LojaIndexRoute
  '/servicos/': typeof ServicosIndexRoute
  '/hub/bolsas/$id': typeof HubBolsasIdRoute
  '/hub/documento/$id': typeof HubDocumentoIdRoute
  '/hub/exames/$id': typeof HubExamesIdRoute
  '/hub/noticias/$id': typeof HubNoticiasIdRoute
  '/loja/pedido/$id': typeof LojaPedidoIdRoute
  '/loja/produto/$id': typeof LojaProdutoIdRoute
  '/hub/bolsas/': typeof HubBolsasIndexRoute
  '/hub/noticias/': typeof HubNoticiasIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/conta': typeof ContaRouteWithChildren
  '/contactos': typeof ContactosRoute
  '/galeria': typeof GaleriaRouteWithChildren
  '/informatica': typeof InformaticaRoute
  '/login': typeof LoginRoute
  '/orcamento': typeof OrcamentoRoute
  '/precos': typeof PrecosRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/redes': typeof RedesRoute
  '/registo': typeof RegistoRoute
  '/sobre': typeof SobreRoute
  '/terms': typeof TermsRoute
  '/balcao/ai-playground': typeof BalcaoAiPlaygroundRoute
  '/balcao/atividade': typeof BalcaoAtividadeRoute
  '/balcao/blog': typeof BalcaoBlogRoute
  '/balcao/bolsas': typeof BalcaoBolsasRoute
  '/balcao/campanhas': typeof BalcaoCampanhasRoute
  '/balcao/cartas': typeof BalcaoCartasRoute
  '/balcao/creditos': typeof BalcaoCreditosRoute
  '/balcao/cv': typeof BalcaoCvRoute
  '/balcao/cv-templates': typeof BalcaoCvTemplatesRoute
  '/balcao/entregas': typeof BalcaoEntregasRoute
  '/balcao/exames': typeof BalcaoExamesRoute
  '/balcao/galeria': typeof BalcaoGaleriaRoute
  '/balcao/hero': typeof BalcaoHeroRoute
  '/balcao/hub': typeof BalcaoHubRoute
  '/balcao/newsletter': typeof BalcaoNewsletterRoute
  '/balcao/noticias': typeof BalcaoNoticiasRoute
  '/balcao/notificacoes': typeof BalcaoNotificacoesRoute
  '/balcao/pagamentos': typeof BalcaoPagamentosRoute
  '/balcao/pedidos': typeof BalcaoPedidosRoute
  '/balcao/precos': typeof BalcaoPrecosRoute
  '/balcao/produtos': typeof BalcaoProdutosRoute
  '/balcao/revisoes': typeof BalcaoRevisoesRoute
  '/balcao/revisoes-precos': typeof BalcaoRevisoesPrecosRoute
  '/balcao/servicos': typeof BalcaoServicosRoute
  '/balcao/stock': typeof BalcaoStockRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/conta/revisoes': typeof ContaRevisoesRoute
  '/galeria/$slug': typeof GaleriaSlugRoute
  '/hub/cartas': typeof HubCartasRoute
  '/hub/creditos': typeof HubCreditosRoute
  '/hub/cv': typeof HubCvRoute
  '/hub/documentos': typeof HubDocumentosRoute
  '/hub/exames': typeof HubExamesRouteWithChildren
  '/hub/explorar': typeof HubExplorarRoute
  '/hub/favoritos': typeof HubFavoritosRoute
  '/hub/upload': typeof HubUploadRoute
  '/loja/carrinho': typeof LojaCarrinhoRoute
  '/loja/checkout': typeof LojaCheckoutRoute
  '/loja/papelaria': typeof LojaPapelariaRoute
  '/servicos/$slug': typeof ServicosSlugRoute
  '/balcao': typeof BalcaoIndexRoute
  '/blog': typeof BlogIndexRoute
  '/hub': typeof HubIndexRoute
  '/loja': typeof LojaIndexRoute
  '/servicos': typeof ServicosIndexRoute
  '/hub/bolsas/$id': typeof HubBolsasIdRoute
  '/hub/documento/$id': typeof HubDocumentoIdRoute
  '/hub/exames/$id': typeof HubExamesIdRoute
  '/hub/noticias/$id': typeof HubNoticiasIdRoute
  '/loja/pedido/$id': typeof LojaPedidoIdRoute
  '/loja/produto/$id': typeof LojaProdutoIdRoute
  '/hub/bolsas': typeof HubBolsasIndexRoute
  '/hub/noticias': typeof HubNoticiasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/balcao': typeof BalcaoRouteWithChildren
  '/conta': typeof ContaRouteWithChildren
  '/contactos': typeof ContactosRoute
  '/galeria': typeof GaleriaRouteWithChildren
  '/informatica': typeof InformaticaRoute
  '/login': typeof LoginRoute
  '/orcamento': typeof OrcamentoRoute
  '/precos': typeof PrecosRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/redes': typeof RedesRoute
  '/registo': typeof RegistoRoute
  '/servicos': typeof ServicosRouteWithChildren
  '/sobre': typeof SobreRoute
  '/terms': typeof TermsRoute
  '/balcao/ai-playground': typeof BalcaoAiPlaygroundRoute
  '/balcao/atividade': typeof BalcaoAtividadeRoute
  '/balcao/blog': typeof BalcaoBlogRoute
  '/balcao/bolsas': typeof BalcaoBolsasRoute
  '/balcao/campanhas': typeof BalcaoCampanhasRoute
  '/balcao/cartas': typeof BalcaoCartasRoute
  '/balcao/creditos': typeof BalcaoCreditosRoute
  '/balcao/cv': typeof BalcaoCvRoute
  '/balcao/cv-templates': typeof BalcaoCvTemplatesRoute
  '/balcao/entregas': typeof BalcaoEntregasRoute
  '/balcao/exames': typeof BalcaoExamesRoute
  '/balcao/galeria': typeof BalcaoGaleriaRoute
  '/balcao/hero': typeof BalcaoHeroRoute
  '/balcao/hub': typeof BalcaoHubRoute
  '/balcao/newsletter': typeof BalcaoNewsletterRoute
  '/balcao/noticias': typeof BalcaoNoticiasRoute
  '/balcao/notificacoes': typeof BalcaoNotificacoesRoute
  '/balcao/pagamentos': typeof BalcaoPagamentosRoute
  '/balcao/pedidos': typeof BalcaoPedidosRoute
  '/balcao/precos': typeof BalcaoPrecosRoute
  '/balcao/produtos': typeof BalcaoProdutosRoute
  '/balcao/revisoes': typeof BalcaoRevisoesRoute
  '/balcao/revisoes-precos': typeof BalcaoRevisoesPrecosRoute
  '/balcao/servicos': typeof BalcaoServicosRoute
  '/balcao/stock': typeof BalcaoStockRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/conta/revisoes': typeof ContaRevisoesRoute
  '/galeria/$slug': typeof GaleriaSlugRoute
  '/hub/bolsas': typeof HubBolsasRouteWithChildren
  '/hub/cartas': typeof HubCartasRoute
  '/hub/creditos': typeof HubCreditosRoute
  '/hub/cv': typeof HubCvRoute
  '/hub/documentos': typeof HubDocumentosRoute
  '/hub/exames': typeof HubExamesRouteWithChildren
  '/hub/explorar': typeof HubExplorarRoute
  '/hub/favoritos': typeof HubFavoritosRoute
  '/hub/noticias': typeof HubNoticiasRouteWithChildren
  '/hub/upload': typeof HubUploadRoute
  '/loja/carrinho': typeof LojaCarrinhoRoute
  '/loja/checkout': typeof LojaCheckoutRoute
  '/loja/papelaria': typeof LojaPapelariaRoute
  '/servicos/$slug': typeof ServicosSlugRoute
  '/balcao/': typeof BalcaoIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/hub/': typeof HubIndexRoute
  '/loja/': typeof LojaIndexRoute
  '/servicos/': typeof ServicosIndexRoute
  '/hub/bolsas/$id': typeof HubBolsasIdRoute
  '/hub/documento/$id': typeof HubDocumentoIdRoute
  '/hub/exames/$id': typeof HubExamesIdRoute
  '/hub/noticias/$id': typeof HubNoticiasIdRoute
  '/loja/pedido/$id': typeof LojaPedidoIdRoute
  '/loja/produto/$id': typeof LojaProdutoIdRoute
  '/hub/bolsas/': typeof HubBolsasIndexRoute
  '/hub/noticias/': typeof HubNoticiasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/balcao'
    | '/conta'
    | '/contactos'
    | '/galeria'
    | '/informatica'
    | '/login'
    | '/orcamento'
    | '/precos'
    | '/privacy-policy'
    | '/redes'
    | '/registo'
    | '/servicos'
    | '/sobre'
    | '/terms'
    | '/balcao/ai-playground'
    | '/balcao/atividade'
    | '/balcao/blog'
    | '/balcao/bolsas'
    | '/balcao/campanhas'
    | '/balcao/cartas'
    | '/balcao/creditos'
    | '/balcao/cv'
    | '/balcao/cv-templates'
    | '/balcao/entregas'
    | '/balcao/exames'
    | '/balcao/galeria'
    | '/balcao/hero'
    | '/balcao/hub'
    | '/balcao/newsletter'
    | '/balcao/noticias'
    | '/balcao/notificacoes'
    | '/balcao/pagamentos'
    | '/balcao/pedidos'
    | '/balcao/precos'
    | '/balcao/produtos'
    | '/balcao/revisoes'
    | '/balcao/revisoes-precos'
    | '/balcao/servicos'
    | '/balcao/stock'
    | '/blog/$slug'
    | '/conta/revisoes'
    | '/galeria/$slug'
    | '/hub/bolsas'
    | '/hub/cartas'
    | '/hub/creditos'
    | '/hub/cv'
    | '/hub/documentos'
    | '/hub/exames'
    | '/hub/explorar'
    | '/hub/favoritos'
    | '/hub/noticias'
    | '/hub/upload'
    | '/loja/carrinho'
    | '/loja/checkout'
    | '/loja/papelaria'
    | '/servicos/$slug'
    | '/balcao/'
    | '/blog/'
    | '/hub/'
    | '/loja/'
    | '/servicos/'
    | '/hub/bolsas/$id'
    | '/hub/documento/$id'
    | '/hub/exames/$id'
    | '/hub/noticias/$id'
    | '/loja/pedido/$id'
    | '/loja/produto/$id'
    | '/hub/bolsas/'
    | '/hub/noticias/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/conta'
    | '/contactos'
    | '/galeria'
    | '/informatica'
    | '/login'
    | '/orcamento'
    | '/precos'
    | '/privacy-policy'
    | '/redes'
    | '/registo'
    | '/sobre'
    | '/terms'
    | '/balcao/ai-playground'
    | '/balcao/atividade'
    | '/balcao/blog'
    | '/balcao/bolsas'
    | '/balcao/campanhas'
    | '/balcao/cartas'
    | '/balcao/creditos'
    | '/balcao/cv'
    | '/balcao/cv-templates'
    | '/balcao/entregas'
    | '/balcao/exames'
    | '/balcao/galeria'
    | '/balcao/hero'
    | '/balcao/hub'
    | '/balcao/newsletter'
    | '/balcao/noticias'
    | '/balcao/notificacoes'
    | '/balcao/pagamentos'
    | '/balcao/pedidos'
    | '/balcao/precos'
    | '/balcao/produtos'
    | '/balcao/revisoes'
    | '/balcao/revisoes-precos'
    | '/balcao/servicos'
    | '/balcao/stock'
    | '/blog/$slug'
    | '/conta/revisoes'
    | '/galeria/$slug'
    | '/hub/cartas'
    | '/hub/creditos'
    | '/hub/cv'
    | '/hub/documentos'
    | '/hub/exames'
    | '/hub/explorar'
    | '/hub/favoritos'
    | '/hub/upload'
    | '/loja/carrinho'
    | '/loja/checkout'
    | '/loja/papelaria'
    | '/servicos/$slug'
    | '/balcao'
    | '/blog'
    | '/hub'
    | '/loja'
    | '/servicos'
    | '/hub/bolsas/$id'
    | '/hub/documento/$id'
    | '/hub/exames/$id'
    | '/hub/noticias/$id'
    | '/loja/pedido/$id'
    | '/loja/produto/$id'
    | '/hub/bolsas'
    | '/hub/noticias'
  id:
    | '__root__'
    | '/'
    | '/balcao'
    | '/conta'
    | '/contactos'
    | '/galeria'
    | '/informatica'
    | '/login'
    | '/orcamento'
    | '/precos'
    | '/privacy-policy'
    | '/redes'
    | '/registo'
    | '/servicos'
    | '/sobre'
    | '/terms'
    | '/balcao/ai-playground'
    | '/balcao/atividade'
    | '/balcao/blog'
    | '/balcao/bolsas'
    | '/balcao/campanhas'
    | '/balcao/cartas'
    | '/balcao/creditos'
    | '/balcao/cv'
    | '/balcao/cv-templates'
    | '/balcao/entregas'
    | '/balcao/exames'
    | '/balcao/galeria'
    | '/balcao/hero'
    | '/balcao/hub'
    | '/balcao/newsletter'
    | '/balcao/noticias'
    | '/balcao/notificacoes'
    | '/balcao/pagamentos'
    | '/balcao/pedidos'
    | '/balcao/precos'
    | '/balcao/produtos'
    | '/balcao/revisoes'
    | '/balcao/revisoes-precos'
    | '/balcao/servicos'
    | '/balcao/stock'
    | '/blog/$slug'
    | '/conta/revisoes'
    | '/galeria/$slug'
    | '/hub/bolsas'
    | '/hub/cartas'
    | '/hub/creditos'
    | '/hub/cv'
    | '/hub/documentos'
    | '/hub/exames'
    | '/hub/explorar'
    | '/hub/favoritos'
    | '/hub/noticias'
    | '/hub/upload'
    | '/loja/carrinho'
    | '/loja/checkout'
    | '/loja/papelaria'
    | '/servicos/$slug'
    | '/balcao/'
    | '/blog/'
    | '/hub/'
    | '/loja/'
    | '/servicos/'
    | '/hub/bolsas/$id'
    | '/hub/documento/$id'
    | '/hub/exames/$id'
    | '/hub/noticias/$id'
    | '/loja/pedido/$id'
    | '/loja/produto/$id'
    | '/hub/bolsas/'
    | '/hub/noticias/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BalcaoRoute: typeof BalcaoRouteWithChildren
  ContaRoute: typeof ContaRouteWithChildren
  ContactosRoute: typeof ContactosRoute
  GaleriaRoute: typeof GaleriaRouteWithChildren
  InformaticaRoute: typeof InformaticaRoute
  LoginRoute: typeof LoginRoute
  OrcamentoRoute: typeof OrcamentoRoute
  PrecosRoute: typeof PrecosRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  RedesRoute: typeof RedesRoute
  RegistoRoute: typeof RegistoRoute
  ServicosRoute: typeof ServicosRouteWithChildren
  SobreRoute: typeof SobreRoute
  TermsRoute: typeof TermsRoute
  BlogSlugRoute: typeof BlogSlugRoute
  HubBolsasRoute: typeof HubBolsasRouteWithChildren
  HubCartasRoute: typeof HubCartasRoute
  HubCreditosRoute: typeof HubCreditosRoute
  HubCvRoute: typeof HubCvRoute
  HubDocumentosRoute: typeof HubDocumentosRoute
  HubExamesRoute: typeof HubExamesRouteWithChildren
  HubExplorarRoute: typeof HubExplorarRoute
  HubFavoritosRoute: typeof HubFavoritosRoute
  HubNoticiasRoute: typeof HubNoticiasRouteWithChildren
  HubUploadRoute: typeof HubUploadRoute
  LojaCarrinhoRoute: typeof LojaCarrinhoRoute
  LojaCheckoutRoute: typeof LojaCheckoutRoute
  LojaPapelariaRoute: typeof LojaPapelariaRoute
  BlogIndexRoute: typeof BlogIndexRoute
  HubIndexRoute: typeof HubIndexRoute
  LojaIndexRoute: typeof LojaIndexRoute
  HubDocumentoIdRoute: typeof HubDocumentoIdRoute
  LojaPedidoIdRoute: typeof LojaPedidoIdRoute
  LojaProdutoIdRoute: typeof LojaProdutoIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicos': {
      id: '/servicos'
      path: '/servicos'
      fullPath: '/servicos'
      preLoaderRoute: typeof ServicosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registo': {
      id: '/registo'
      path: '/registo'
      fullPath: '/registo'
      preLoaderRoute: typeof RegistoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redes': {
      id: '/redes'
      path: '/redes'
      fullPath: '/redes'
      preLoaderRoute: typeof RedesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/precos': {
      id: '/precos'
      path: '/precos'
      fullPath: '/precos'
      preLoaderRoute: typeof PrecosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orcamento': {
      id: '/orcamento'
      path: '/orcamento'
      fullPath: '/orcamento'
      preLoaderRoute: typeof OrcamentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/informatica': {
      id: '/informatica'
      path: '/informatica'
      fullPath: '/informatica'
      preLoaderRoute: typeof InformaticaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/galeria': {
      id: '/galeria'
      path: '/galeria'
      fullPath: '/galeria'
      preLoaderRoute: typeof GaleriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contactos': {
      id: '/contactos'
      path: '/contactos'
      fullPath: '/contactos'
      preLoaderRoute: typeof ContactosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conta': {
      id: '/conta'
      path: '/conta'
      fullPath: '/conta'
      preLoaderRoute: typeof ContaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/balcao': {
      id: '/balcao'
      path: '/balcao'
      fullPath: '/balcao'
      preLoaderRoute: typeof BalcaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicos/': {
      id: '/servicos/'
      path: '/'
      fullPath: '/servicos/'
      preLoaderRoute: typeof ServicosIndexRouteImport
      parentRoute: typeof ServicosRoute
    }
    '/loja/': {
      id: '/loja/'
      path: '/loja'
      fullPath: '/loja/'
      preLoaderRoute: typeof LojaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hub/': {
      id: '/hub/'
      path: '/hub'
      fullPath: '/hub/'
      preLoaderRoute: typeof HubIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/balcao/': {
      id: '/balcao/'
      path: '/'
      fullPath: '/balcao/'
      preLoaderRoute: typeof BalcaoIndexRouteImport
      parentRoute: typeof BalcaoRoute
    }
    '/servicos/$slug': {
      id: '/servicos/$slug'
      path: '/$slug'
      fullPath: '/servicos/$slug'
      preLoaderRoute: typeof ServicosSlugRouteImport
      parentRoute: typeof ServicosRoute
    }
    '/loja/papelaria': {
      id: '/loja/papelaria'
      path: '/loja/papelaria'
      fullPath: '/loja/papelaria'
      preLoaderRoute: typeof LojaPapelariaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loja/checkout': {
      id: '/loja/checkout'
      path: '/loja/checkout'
      fullPath: '/loja/checkout'
      preLoaderRoute: typeof LojaCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loja/carrinho': {
      id: '/loja/carrinho'
      path: '/loja/carrinho'
      fullPath: '/loja/carrinho'
      preLoaderRoute: typeof LojaCarrinhoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hub/upload': {
      id: '/hub/upload'
      path: '/hub/upload'
      fullPath: '/hub/upload'
      preLoaderRoute: typeof HubUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hub/noticias': {
      id: '/hub/noticias'
      path: '/hub/noticias'
      fullPath: '/hub/noticias'
      preLoaderRoute: typeof HubNoticiasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hub/favoritos': {
      id: '/hub/favoritos'
      path: '/hub/favoritos'
      fullPath: '/hub/favoritos'
      preLoaderRoute: typeof HubFavoritosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hub/explorar': {
      id: '/hub/explorar'
      path: '/hub/explorar'
      fullPath: '/hub/explorar'
      preLoaderRoute: typeof HubExplorarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hub/exames': {
      id: '/hub/exames'
      path: '/hub/exames'
      fullPath: '/hub/exames'
      preLoaderRoute: typeof HubExamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hub/documentos': {
      id: '/hub/documentos'
      path: '/hub/documentos'
      fullPath: '/hub/documentos'
      preLoaderRoute: typeof HubDocumentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hub/cv': {
      id: '/hub/cv'
      path: '/hub/cv'
      fullPath: '/hub/cv'
      preLoaderRoute: typeof HubCvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hub/creditos': {
      id: '/hub/creditos'
      path: '/hub/creditos'
      fullPath: '/hub/creditos'
      preLoaderRoute: typeof HubCreditosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hub/cartas': {
      id: '/hub/cartas'
      path: '/hub/cartas'
      fullPath: '/hub/cartas'
      preLoaderRoute: typeof HubCartasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hub/bolsas': {
      id: '/hub/bolsas'
      path: '/hub/bolsas'
      fullPath: '/hub/bolsas'
      preLoaderRoute: typeof HubBolsasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/galeria/$slug': {
      id: '/galeria/$slug'
      path: '/$slug'
      fullPath: '/galeria/$slug'
      preLoaderRoute: typeof GaleriaSlugRouteImport
      parentRoute: typeof GaleriaRoute
    }
    '/conta/revisoes': {
      id: '/conta/revisoes'
      path: '/revisoes'
      fullPath: '/conta/revisoes'
      preLoaderRoute: typeof ContaRevisoesRouteImport
      parentRoute: typeof ContaRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/balcao/stock': {
      id: '/balcao/stock'
      path: '/stock'
      fullPath: '/balcao/stock'
      preLoaderRoute: typeof BalcaoStockRouteImport
      parentRoute: typeof BalcaoRoute
    }
    '/balcao/servicos': {
      id: '/balcao/servicos'
      path: '/servicos'
      fullPath: '/balcao/servicos'
      preLoaderRoute: typeof BalcaoServicosRouteImport
      parentRoute: typeof BalcaoRoute
    }
    '/balcao/revisoes-precos': {
      id: '/balcao/revisoes-precos'
      path: '/revisoes-precos'
      fullPath: '/balcao/revisoes-precos'
      preLoaderRoute: typeof BalcaoRevisoesPrecosRouteImport
      parentRoute: typeof BalcaoRoute
    }
    '/balcao/revisoes': {
      id: '/balcao/revisoes'
      path: '/revisoes'
      fullPath: '/balcao/revisoes'
      preLoaderRoute: typeof BalcaoRevisoesRouteImport
      parentRoute: typeof BalcaoRoute
    }
    '/balcao/produtos': {
      id: '/balcao/produtos'
      path: '/produtos'
      fullPath: '/balcao/produtos'
      preLoaderRoute: typeof BalcaoProdutosRouteImport
      parentRoute: typeof BalcaoRoute
    }
    '/balcao/precos': {
      id: '/balcao/precos'
      path: '/precos'
      fullPath: '/balcao/precos'
      preLoaderRoute: typeof BalcaoPrecosRouteImport
      parentRoute: typeof BalcaoRoute
    }
    '/balcao/pedidos': {
      id: '/balcao/pedidos'
      path: '/pedidos'
      fullPath: '/balcao/pedidos'
      preLoaderRoute: typeof BalcaoPedidosRouteImport
      parentRoute: typeof BalcaoRoute
    }
    '/balcao/pagamentos': {
      id: '/balcao/pagamentos'
      path: '/pagamentos'
      fullPath: '/balcao/pagamentos'
      preLoaderRoute: typeof BalcaoPagamentosRouteImport
      parentRoute: typeof BalcaoRoute
    }
    '/balcao/notificacoes': {
      id: '/balcao/notificacoes'
      path: '/notificacoes'
      fullPath: '/balcao/notificacoes'
      preLoaderRoute: typeof BalcaoNotificacoesRouteImport
      parentRoute: typeof BalcaoRoute
    }
    '/balcao/noticias': {
      id: '/balcao/noticias'
      path: '/noticias'
      fullPath: '/balcao/noticias'
      preLoaderRoute: typeof BalcaoNoticiasRouteImport
      parentRoute: typeof BalcaoRoute
    }
    '/balcao/newsletter': {
      id: '/balcao/newsletter'
      path: '/newsletter'
      fullPath: '/balcao/newsletter'
      preLoaderRoute: typeof BalcaoNewsletterRouteImport
      parentRoute: typeof BalcaoRoute
    }
    '/balcao/hub': {
      id: '/balcao/hub'
      path: '/hub'
      fullPath: '/balcao/hub'
      preLoaderRoute: typeof BalcaoHubRouteImport
      parentRoute: typeof BalcaoRoute
    }
    '/balcao/hero': {
      id: '/balcao/hero'
      path: '/hero'
      fullPath: '/balcao/hero'
      preLoaderRoute: typeof BalcaoHeroRouteImport
      parentRoute: typeof BalcaoRoute
    }
    '/balcao/galeria': {
      id: '/balcao/galeria'
      path: '/galeria'
      fullPath: '/balcao/galeria'
      preLoaderRoute: typeof BalcaoGaleriaRouteImport
      parentRoute: typeof BalcaoRoute
    }
    '/balcao/exames': {
      id: '/balcao/exames'
      path: '/exames'
      fullPath: '/balcao/exames'
      preLoaderRoute: typeof BalcaoExamesRouteImport
      parentRoute: typeof BalcaoRoute
    }
    '/balcao/entregas': {
      id: '/balcao/entregas'
      path: '/entregas'
      fullPath: '/balcao/entregas'
      preLoaderRoute: typeof BalcaoEntregasRouteImport
      parentRoute: typeof BalcaoRoute
    }
    '/balcao/cv-templates': {
      id: '/balcao/cv-templates'
      path: '/cv-templates'
      fullPath: '/balcao/cv-templates'
      preLoaderRoute: typeof BalcaoCvTemplatesRouteImport
      parentRoute: typeof BalcaoRoute
    }
    '/balcao/cv': {
      id: '/balcao/cv'
      path: '/cv'
      fullPath: '/balcao/cv'
      preLoaderRoute: typeof BalcaoCvRouteImport
      parentRoute: typeof BalcaoRoute
    }
    '/balcao/creditos': {
      id: '/balcao/creditos'
      path: '/creditos'
      fullPath: '/balcao/creditos'
      preLoaderRoute: typeof BalcaoCreditosRouteImport
      parentRoute: typeof BalcaoRoute
    }
    '/balcao/cartas': {
      id: '/balcao/cartas'
      path: '/cartas'
      fullPath: '/balcao/cartas'
      preLoaderRoute: typeof BalcaoCartasRouteImport
      parentRoute: typeof BalcaoRoute
    }
    '/balcao/campanhas': {
      id: '/balcao/campanhas'
      path: '/campanhas'
      fullPath: '/balcao/campanhas'
      preLoaderRoute: typeof BalcaoCampanhasRouteImport
      parentRoute: typeof BalcaoRoute
    }
    '/balcao/bolsas': {
      id: '/balcao/bolsas'
      path: '/bolsas'
      fullPath: '/balcao/bolsas'
      preLoaderRoute: typeof BalcaoBolsasRouteImport
      parentRoute: typeof BalcaoRoute
    }
    '/balcao/blog': {
      id: '/balcao/blog'
      path: '/blog'
      fullPath: '/balcao/blog'
      preLoaderRoute: typeof BalcaoBlogRouteImport
      parentRoute: typeof BalcaoRoute
    }
    '/balcao/atividade': {
      id: '/balcao/atividade'
      path: '/atividade'
      fullPath: '/balcao/atividade'
      preLoaderRoute: typeof BalcaoAtividadeRouteImport
      parentRoute: typeof BalcaoRoute
    }
    '/balcao/ai-playground': {
      id: '/balcao/ai-playground'
      path: '/ai-playground'
      fullPath: '/balcao/ai-playground'
      preLoaderRoute: typeof BalcaoAiPlaygroundRouteImport
      parentRoute: typeof BalcaoRoute
    }
    '/hub/noticias/': {
      id: '/hub/noticias/'
      path: '/'
      fullPath: '/hub/noticias/'
      preLoaderRoute: typeof HubNoticiasIndexRouteImport
      parentRoute: typeof HubNoticiasRoute
    }
    '/hub/bolsas/': {
      id: '/hub/bolsas/'
      path: '/'
      fullPath: '/hub/bolsas/'
      preLoaderRoute: typeof HubBolsasIndexRouteImport
      parentRoute: typeof HubBolsasRoute
    }
    '/loja/produto/$id': {
      id: '/loja/produto/$id'
      path: '/loja/produto/$id'
      fullPath: '/loja/produto/$id'
      preLoaderRoute: typeof LojaProdutoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loja/pedido/$id': {
      id: '/loja/pedido/$id'
      path: '/loja/pedido/$id'
      fullPath: '/loja/pedido/$id'
      preLoaderRoute: typeof LojaPedidoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hub/noticias/$id': {
      id: '/hub/noticias/$id'
      path: '/$id'
      fullPath: '/hub/noticias/$id'
      preLoaderRoute: typeof HubNoticiasIdRouteImport
      parentRoute: typeof HubNoticiasRoute
    }
    '/hub/exames/$id': {
      id: '/hub/exames/$id'
      path: '/$id'
      fullPath: '/hub/exames/$id'
      preLoaderRoute: typeof HubExamesIdRouteImport
      parentRoute: typeof HubExamesRoute
    }
    '/hub/documento/$id': {
      id: '/hub/documento/$id'
      path: '/hub/documento/$id'
      fullPath: '/hub/documento/$id'
      preLoaderRoute: typeof HubDocumentoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hub/bolsas/$id': {
      id: '/hub/bolsas/$id'
      path: '/$id'
      fullPath: '/hub/bolsas/$id'
      preLoaderRoute: typeof HubBolsasIdRouteImport
      parentRoute: typeof HubBolsasRoute
    }
  }
}

interface BalcaoRouteChildren {
  BalcaoAiPlaygroundRoute: typeof BalcaoAiPlaygroundRoute
  BalcaoAtividadeRoute: typeof BalcaoAtividadeRoute
  BalcaoBlogRoute: typeof BalcaoBlogRoute
  BalcaoBolsasRoute: typeof BalcaoBolsasRoute
  BalcaoCampanhasRoute: typeof BalcaoCampanhasRoute
  BalcaoCartasRoute: typeof BalcaoCartasRoute
  BalcaoCreditosRoute: typeof BalcaoCreditosRoute
  BalcaoCvRoute: typeof BalcaoCvRoute
  BalcaoCvTemplatesRoute: typeof BalcaoCvTemplatesRoute
  BalcaoEntregasRoute: typeof BalcaoEntregasRoute
  BalcaoExamesRoute: typeof BalcaoExamesRoute
  BalcaoGaleriaRoute: typeof BalcaoGaleriaRoute
  BalcaoHeroRoute: typeof BalcaoHeroRoute
  BalcaoHubRoute: typeof BalcaoHubRoute
  BalcaoNewsletterRoute: typeof BalcaoNewsletterRoute
  BalcaoNoticiasRoute: typeof BalcaoNoticiasRoute
  BalcaoNotificacoesRoute: typeof BalcaoNotificacoesRoute
  BalcaoPagamentosRoute: typeof BalcaoPagamentosRoute
  BalcaoPedidosRoute: typeof BalcaoPedidosRoute
  BalcaoPrecosRoute: typeof BalcaoPrecosRoute
  BalcaoProdutosRoute: typeof BalcaoProdutosRoute
  BalcaoRevisoesRoute: typeof BalcaoRevisoesRoute
  BalcaoRevisoesPrecosRoute: typeof BalcaoRevisoesPrecosRoute
  BalcaoServicosRoute: typeof BalcaoServicosRoute
  BalcaoStockRoute: typeof BalcaoStockRoute
  BalcaoIndexRoute: typeof BalcaoIndexRoute
}

const BalcaoRouteChildren: BalcaoRouteChildren = {
  BalcaoAiPlaygroundRoute: BalcaoAiPlaygroundRoute,
  BalcaoAtividadeRoute: BalcaoAtividadeRoute,
  BalcaoBlogRoute: BalcaoBlogRoute,
  BalcaoBolsasRoute: BalcaoBolsasRoute,
  BalcaoCampanhasRoute: BalcaoCampanhasRoute,
  BalcaoCartasRoute: BalcaoCartasRoute,
  BalcaoCreditosRoute: BalcaoCreditosRoute,
  BalcaoCvRoute: BalcaoCvRoute,
  BalcaoCvTemplatesRoute: BalcaoCvTemplatesRoute,
  BalcaoEntregasRoute: BalcaoEntregasRoute,
  BalcaoExamesRoute: BalcaoExamesRoute,
  BalcaoGaleriaRoute: BalcaoGaleriaRoute,
  BalcaoHeroRoute: BalcaoHeroRoute,
  BalcaoHubRoute: BalcaoHubRoute,
  BalcaoNewsletterRoute: BalcaoNewsletterRoute,
  BalcaoNoticiasRoute: BalcaoNoticiasRoute,
  BalcaoNotificacoesRoute: BalcaoNotificacoesRoute,
  BalcaoPagamentosRoute: BalcaoPagamentosRoute,
  BalcaoPedidosRoute: BalcaoPedidosRoute,
  BalcaoPrecosRoute: BalcaoPrecosRoute,
  BalcaoProdutosRoute: BalcaoProdutosRoute,
  BalcaoRevisoesRoute: BalcaoRevisoesRoute,
  BalcaoRevisoesPrecosRoute: BalcaoRevisoesPrecosRoute,
  BalcaoServicosRoute: BalcaoServicosRoute,
  BalcaoStockRoute: BalcaoStockRoute,
  BalcaoIndexRoute: BalcaoIndexRoute,
}

const BalcaoRouteWithChildren =
  BalcaoRoute._addFileChildren(BalcaoRouteChildren)

interface ContaRouteChildren {
  ContaRevisoesRoute: typeof ContaRevisoesRoute
}

const ContaRouteChildren: ContaRouteChildren = {
  ContaRevisoesRoute: ContaRevisoesRoute,
}

const ContaRouteWithChildren = ContaRoute._addFileChildren(ContaRouteChildren)

interface GaleriaRouteChildren {
  GaleriaSlugRoute: typeof GaleriaSlugRoute
}

const GaleriaRouteChildren: GaleriaRouteChildren = {
  GaleriaSlugRoute: GaleriaSlugRoute,
}

const GaleriaRouteWithChildren =
  GaleriaRoute._addFileChildren(GaleriaRouteChildren)

interface ServicosRouteChildren {
  ServicosSlugRoute: typeof ServicosSlugRoute
  ServicosIndexRoute: typeof ServicosIndexRoute
}

const ServicosRouteChildren: ServicosRouteChildren = {
  ServicosSlugRoute: ServicosSlugRoute,
  ServicosIndexRoute: ServicosIndexRoute,
}

const ServicosRouteWithChildren = ServicosRoute._addFileChildren(
  ServicosRouteChildren,
)

interface HubBolsasRouteChildren {
  HubBolsasIdRoute: typeof HubBolsasIdRoute
  HubBolsasIndexRoute: typeof HubBolsasIndexRoute
}

const HubBolsasRouteChildren: HubBolsasRouteChildren = {
  HubBolsasIdRoute: HubBolsasIdRoute,
  HubBolsasIndexRoute: HubBolsasIndexRoute,
}

const HubBolsasRouteWithChildren = HubBolsasRoute._addFileChildren(
  HubBolsasRouteChildren,
)

interface HubExamesRouteChildren {
  HubExamesIdRoute: typeof HubExamesIdRoute
}

const HubExamesRouteChildren: HubExamesRouteChildren = {
  HubExamesIdRoute: HubExamesIdRoute,
}

const HubExamesRouteWithChildren = HubExamesRoute._addFileChildren(
  HubExamesRouteChildren,
)

interface HubNoticiasRouteChildren {
  HubNoticiasIdRoute: typeof HubNoticiasIdRoute
  HubNoticiasIndexRoute: typeof HubNoticiasIndexRoute
}

const HubNoticiasRouteChildren: HubNoticiasRouteChildren = {
  HubNoticiasIdRoute: HubNoticiasIdRoute,
  HubNoticiasIndexRoute: HubNoticiasIndexRoute,
}

const HubNoticiasRouteWithChildren = HubNoticiasRoute._addFileChildren(
  HubNoticiasRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BalcaoRoute: BalcaoRouteWithChildren,
  ContaRoute: ContaRouteWithChildren,
  ContactosRoute: ContactosRoute,
  GaleriaRoute: GaleriaRouteWithChildren,
  InformaticaRoute: InformaticaRoute,
  LoginRoute: LoginRoute,
  OrcamentoRoute: OrcamentoRoute,
  PrecosRoute: PrecosRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  RedesRoute: RedesRoute,
  RegistoRoute: RegistoRoute,
  ServicosRoute: ServicosRouteWithChildren,
  SobreRoute: SobreRoute,
  TermsRoute: TermsRoute,
  BlogSlugRoute: BlogSlugRoute,
  HubBolsasRoute: HubBolsasRouteWithChildren,
  HubCartasRoute: HubCartasRoute,
  HubCreditosRoute: HubCreditosRoute,
  HubCvRoute: HubCvRoute,
  HubDocumentosRoute: HubDocumentosRoute,
  HubExamesRoute: HubExamesRouteWithChildren,
  HubExplorarRoute: HubExplorarRoute,
  HubFavoritosRoute: HubFavoritosRoute,
  HubNoticiasRoute: HubNoticiasRouteWithChildren,
  HubUploadRoute: HubUploadRoute,
  LojaCarrinhoRoute: LojaCarrinhoRoute,
  LojaCheckoutRoute: LojaCheckoutRoute,
  LojaPapelariaRoute: LojaPapelariaRoute,
  BlogIndexRoute: BlogIndexRoute,
  HubIndexRoute: HubIndexRoute,
  LojaIndexRoute: LojaIndexRoute,
  HubDocumentoIdRoute: HubDocumentoIdRoute,
  LojaPedidoIdRoute: LojaPedidoIdRoute,
  LojaProdutoIdRoute: LojaProdutoIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
